Class Demo.WS.Test.Response.GetAllergyByMRNResponse Extends Ens.Response [ ProcedureBlock ]
{

Property GetAllergyByMRNResult As %String;

Storage Default
{
<Data name="GetAllergyByMRNResponseDefaultData">
<Subscript>"GetAllergyByMRNResponse"</Subscript>
<Value name="1">
<Value>GetAllergyByMRNResult</Value>
</Value>
</Data>
<DefaultData>GetAllergyByMRNResponseDefaultData</DefaultData>
<Type>%Storage.Persistent</Type>
}

}
